name: ci
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: read
  issues: write         # posting and hiding bot comments
  pull-requests: write  # posting and hiding bot comments

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ALPINE_VERSION: ["3.20"]
        ROS_DISTRO: ["humble", "jazzy"]
    uses: alpine-ros/alpine-ros-ci-workflows/.github/workflows/ros2.yaml@main
    with:
      enable-bot-comment: true
      alpine-version: ${{ matrix.ALPINE_VERSION }}
      ros-distro: ${{ matrix.ROS_DISTRO }}
    secrets:
      bot-comment-token: ${{ secrets.GITHUB_TOKEN }}
